include: package:lint/strict.yaml
analyzer:
  exclude:
    - lib/generated/**
    - "**.g.dart"
  errors:
    todo: ignore

linter:
  rules:
    avoid_classes_with_only_static_members: false
    prefer_single_quotes: true
    close_sinks: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    unnecessary_constructor_name: true
    flutter_style_todos: true
    no_wildcard_variable_uses: true
    avoid_catches_without_on_clauses: true
    unawaited_futures: true
    always_put_required_named_parameters_first: true
    unnecessary_lambdas: true
